/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

import dev.futurepath.controllers.OutcomingMsgController;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Daniel el Gomas
 */
public class ChatView extends javax.swing.JPanel {

    private OutcomingMsgController controllerOut;
    private String roomName;
    
    public ChatView(String roomName) {
        initComponents();
        controllerOut = new OutcomingMsgController(this);
        this.roomName = roomName;
    }

    public String getRoomName() {
        return roomName;
    }
    

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTextField getMessageTextField() {
        return messageTextField;
    }

    public void setMessageTextField(JTextField messageTextField) {
        this.messageTextField = messageTextField;
    }

    public JTextArea getMessagesTextArea() {
        return messagesTextArea;
    }

    public void setMessagesTextArea(JTextArea messagesTextArea) {
        this.messagesTextArea = messagesTextArea;
    }

    public JList<String> getUserList() {
        return userList;
    }

    public void setUserList(JList<String> userList) {
        this.userList = userList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        sendButton = new javax.swing.JButton();
        messageTextField = new javax.swing.JTextField();

        setLayout(null);

        messagesTextArea.setEditable(false);
        messagesTextArea.setColumns(20);
        messagesTextArea.setRows(5);
        jScrollPane1.setViewportView(messagesTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 270, 200);

        jScrollPane2.setViewportView(userList);

        add(jScrollPane2);
        jScrollPane2.setBounds(290, 10, 100, 280);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        add(sendButton);
        sendButton.setBounds(200, 230, 70, 40);
        add(messageTextField);
        messageTextField.setBounds(20, 230, 160, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        controllerOut.sendTextMessage(this);
    }//GEN-LAST:event_sendButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JTextArea messagesTextArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
