/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

/**
 *
 * @author DarkP
 */
public class RoomListView extends javax.swing.JPanel {

    /**
     * Creates new form ChatRoomView
     */
    public RoomListView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roomList = new javax.swing.JList<>();
        selectRoomButton = new javax.swing.JButton();

        setLayout(null);

        roomList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(roomList);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 0, 280, 210);

        selectRoomButton.setText("Select Room");
        add(selectRoomButton);
        selectRoomButton.setBounds(110, 220, 180, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> roomList;
    private javax.swing.JButton selectRoomButton;
    // End of variables declaration//GEN-END:variables
}
