/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

/**
 *
 * @author DarkP
 */
public class RoomListView extends javax.swing.JPanel {

    /**
     * Creates new form ChatRoomView
     */
    public RoomListView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roomList = new javax.swing.JList<>();
        selectRoomButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jScrollPane1.setViewportView(roomList);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 380, 180);

        selectRoomButton.setText("Update");
        add(selectRoomButton);
        selectRoomButton.setBounds(130, 250, 170, 40);
        add(jTextField1);
        jTextField1.setBounds(10, 10, 270, 40);

        jButton1.setText("jButton1");
        add(jButton1);
        jButton1.setBounds(290, 10, 100, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> roomList;
    private javax.swing.JButton selectRoomButton;
    // End of variables declaration//GEN-END:variables
}
